### ISSUE TITLE
Create a separate development environment

### ISSUE THREAD

**Issue by JacksonBates** [JacksonBates/pair-backend#1]
We need to have a dev environment that does not affect the production database.

At a minimum, we need something like this (thanks @jenovs):

```
const env = process.env.NODE_ENV || 'development';

if (env === 'development') {
  process.env.PORT = 3000;
  process.env.MONGODB_URI = 'mongodb://localhost:27017/TodoApp'; // replace with appropriate URI
} else if (env === 'test') {
  process.env.PORT = 3000;
  process.env.MONGODB_URI = 'mongodb://localhost:27017/TodoAppTest'; // replace with appropriate URI
}
```

We'd also need to modify the CONTRIBUTING file to explain how to set up the local environment, run tests etc.

Further discussion below is welcome - we won't necessarily rush this one, as it will pay to get it right.

Related to issue 28 from the front end repo: https://github.com/JacksonBates/pair-frontend/issues/28

**Comment by jenovs** [comment]
I'll try to implement it using my newly acquired knowledge (later in the Udemy's course that aforementioned code was tweaked, so it can store passwords, API keys etc.).
