### ISSUE TITLE
Fix the failing tests from convertToMS.test.js in convertToMS.js

### ISSUE THREAD

**Issue by JacksonBates** [JacksonBates/pair-backend#10]
The following tests currently fail:
![image](https://cloud.githubusercontent.com/assets/4337740/20733693/eed2faa2-b6e8-11e6-8e6c-ddec3f7ff0a8.png)

convertToMS.js needs to be improved to address these.

**Comment by JacksonBates** [comment]
Also, regex should match FE as per #7 (now closed in order to merge the issues).

**Comment by BenGitter** [comment]
I can do this. 

I just realized that the test for multiple parameters (in: `test/convertToMS.test.js`) is unnecessary, since the function can only be called from our own code.

**Comment by BenGitter** [comment]
I made 2 pull requests. One to remove the test and one to update convertToMS to pass all tests. convertToMS.js will now pass all tests (except for the multiple parameters test).
