### ISSUE TITLE
Removing the redirects in the post and delete routes renders the app unusable

### ISSUE THREAD

**Issue by JacksonBates** [JacksonBates/pair-backend#14]
Fixes to #6 and #11 did not have the intended consequences.

Currently, once the 'Add' form or the 'Delete' button are submitted, the app redirects to the backend API url and stays there.

To fix this properly, the React component form used to send the data to the API should not 'follow' the data. It should wait quietly for the response and re-render the appropriate DOM element when it is received.

We might be entering redux territory, and is a front end issue.

**In the short term, we should either revert the changes to the redirects introduced by #9 and #13, or keep the app in maintenance mode until all is fixed**. Thoughts?

cc. @BenGitter & @jenovs

**Comment by BenGitter** [comment]
Depends on how long it will take to fix the front-end. If that takes more than a few days, I would suggest reverting. Though the redirecting might cause problems when testing the front-end fix, right?

**Comment by jenovs** [comment]
I think we should revert the changes and add additional routes so we can test them without breaking frontend.

I did some reading on [API design](http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api) and it looks like `VERB /noun` is recommended pattern (`noun` being in plural). So it would be like:

`GET /posts` - to get posts; returns posts
`POST /posts` - to add a post; returns added post
`DELETE /posts/:id` - to delete a post; return success(?)

Thoughts?

**Comment by BenGitter** [comment]
@jenovs, good idea. Maybe we can use the `api/v2` route for that? If so, we might want to place the `routes.js` and the file corresponding with api version 2 in a separate folder `Routes` or `API`?


> to delete a post; return success(?)

I suppose all the API calls should either contain `{status: succes}` or we could just send a `200` status. I believe sending a status like `200` or something else if there was an error, is preferred (but I would have to search for that).

**Comment by BenGitter** [comment]
Found a good article: http://blog.restcase.com/rest-api-error-codes-101/

**Comment by jenovs** [comment]
I think we don't need `v2` just yet, we won't break any existing functionality (http://semver.org/)

So all endpoints should return status in header, and also in response json like this:
`res.send(xxx).json(json_data);` where `json_data = {status: xxx, {...`.

**Comment by BenGitter** [comment]
I agree, that we don't add anything super exciting to the api. On the other hand adding routes to the same file which do the exact same thing, seems a bit sloppy.

I would use:  `json_data = {status: xxx, post: post}` and in case of an error: `json_data = {status: xxx, error: error}`

Not sure if this is a good idea, but maybe we can make a quick documentation to which we can refer when updating the api.

**Comment by JacksonBates** [comment]
I'm gonna go revert the changes to make the app functional again. From there we can get the dev env up and running. Once that's done we can experiment on different branches with local DBs that don't require constant pushes to heroku to confirm the routes work as expected. A real dev environment will let us move quicker and with more automony (presently only I have the mLab keys for the live database. If it were local dbs we were dealing with, I wouldn't be the one slowing things down) (I may have said that elsewhere already)

**Comment by jenovs** [comment]
Created pr with dev and test setups.

Btw tests fail. Function returns time, tests expect date. Any takers?
