### ISSUE TITLE
Add Posts should not allow null or undefined values to be passed to the DB

### ISSUE THREAD

**Issue by JacksonBates** [JacksonBates/pair-backend#23]
See: https://github.com/JacksonBates/pair-frontend/issues/42

There should be default string values to ensure null / undefined data is never passed to the front-end.

**Comment by jenovs** [comment]
Now with mongoose this should be an easy fix.

**Comment by JacksonBates** [comment]
True - I didn't think of that.

For anyone that want's this, the example at the top of http://mongoosejs.com/docs/guide.html shows the syntax for adding a default value to the post.model.js file that contains the schema.

The default string values for setup and interests should be empty strings: `""`
(For now...the setup will eventually be an empty array, I think.)

**Comment by vdineva** [comment]
This issue is actually addressed in my PR: https://github.com/JacksonBates/pair-backend/pull/43/files#diff-62fe234201e39fd6918b79a4893ee504
Once that gets merged, this issue can be closed
