### ISSUE TITLE
Write appropriate tests for convertToMS.js

### ISSUE THREAD

**Issue by JacksonBates** [JacksonBates/pair-backend#3]
This quick function could use a test that ensures that given a range of possible inputs, the correct number of milliseconds is returned.

It should include edge cases where users submit something odd, like 01:75 (i.e. 1 hour 75 mins, which is obviously 2 hours 15 mins)

Mocha is included in the package.json already and `npm test` will run and file that includes the word test.

The convertToMS.js test file should be called `convertToMS.test.js`

**Comment by BenGitter** [comment]
I have no real experience with mocha, but I believe this should be simple enough. 

A few questions: Shouldn't mocha be included under dependencies in package.json? And would it be useful to have the test in a /test directory?

**Comment by JacksonBates** [comment]
@BenGitter Mocha is included in dev-dependencies, which is fine I think.

A dedicated tests folder makes sense too. If you want to include chai for the assertions you can (but don't have to)

Have a crack at it, and feel free to ask any other questions along the way :smile:

**Comment by BenGitter** [comment]
I might miss it, but I don't see it. Anyway, I have added it locally. BTW thanks for merging my pull request!

**Comment by BenGitter** [comment]
Why does the check in the convertToMS.js differ from the one on the frontend?

convertToMS: `!string.match(/[\d{2}:\d{2}]/)`
frontend: `pattern='\d{1,2}:\d{2}'`

Do I miss something or is this an error. Note that convertToMS uses `[]`, which means that as long as the string contains two digits or a `:`, it will return as valid. 

I suppose convertToMS should be changed to be the same as the frontend. Maybe this should be a new issue?

Also, should we test this or can we assume that `string` that is passed into convertToMS is correct (since it was checked on the frontend)?

**Comment by BenGitter** [comment]
At the moment I have simple tests for these inputs:

* 0:00
* 00:00
* 1:01
* 21:59
* 01:75
* 1:75
* 99:99

I think these cover all the cases where the input format is valid.

**Comment by JacksonBates** [comment]
You're right - the convertToMS regex should be improved so that it only allows the format of the strings you've listed above.

You should test for whether it is a string too - don't trust the front end. @jenovs is working on changing aspects of that which might mean it becomes possible to send other data. Besides, someone could currently use Postman or `curl` to circumvent the frontend and send what they like :)

**Comment by JacksonBates** [comment]
@BenGitter I've made the regex issue separate, so you can just focus on the testing for this one.

**Comment by BenGitter** [comment]
And if you set the `Access-Control-Allow-Origin` header to pairboard.surge.sh?

Also, convertToMS will in some cases return "Invalid Date", but in your routes you don't check for it.  

> You should test for whether it is a string too

I can't think of any data type that would pass the test (`/\d{1,2}:\d{2}/`), but I added tests for a Number, Boolean, Array and an Undefined.

I believe I have most test cases. I have added the following:

* 0120
* true
* ['21:20']
* undefined
* '21:20', '1:00' (two parameters, I think the function should return Invalid Date if more than one parameter is given)
* '0120'
* '1:200'
* '01:200'
* '011:200'
* ':20'
* '11:'

Can you think of cases I forgot? Else I will make a pull request.

To your point: Thanks for making the new issue. Should it also include checking:

* if parameter is a string
* if only one is given

**Comment by JacksonBates** [comment]
> And if you set the Access-Control-Allow-Origin header to pairboard.surge.sh?

That's an ongoing headache at the moment. Once #1 is resolved, we can lock up the access control again.

**Comment by JacksonBates** [comment]
> Also, convertToMS will in some cases return "Invalid Date", but in your routes you don't check for it.

Ok - maybe open a new issue for that one?

**Comment by JacksonBates** [comment]
I think the test cases are comprehensive - PR away, and we can always add more esoteric ones later if needed :)

**Comment by JacksonBates** [comment]
I didn't quite understand this bit:
>Should it also include checking:
> + if parameter is a string
> + if only one is given

Do you mean whether the regex in #7 should do those things?

**Comment by BenGitter** [comment]
I think that should be a seperate if statement. Not sure if this is necessary. But if more than one parameter is given, you are sure that someone is hacking around. 

As well as there should be an if statement to check if the parameter is a string. Otherwise the function will give an error, because it uses `.match()` which assumes a string.
