### ISSUE TITLE
Stop the POST /add route from redirecting to pairbord

### ISSUE THREAD

**Issue by JacksonBates** [JacksonBates/pair-backend#6]
Companion to front end issue: https://github.com/JacksonBates/pair-frontend/issues/6

From @jenovs:
> redirect in POST /add route could be easily replaced with res.status(200).send() without any consequences, because page will be refreshed after form submit by default, and then it could be overwritten in js on FE.

**Comment by BenGitter** [comment]
I can fix this (well, everyone can). If anyone else wants to do this, feel free.

**Comment by JacksonBates** [comment]
If no one has claimed it before you finish up the testing PR, and you still have time / fancy it, it's all yours :)
