### ISSUE TITLE
Improve the regex in convertToMS.js

### ISSUE THREAD

**Issue by JacksonBates** [JacksonBates/pair-backend#7]
The regex from this function should match the regex pattern from front-end.

See https://github.com/JacksonBates/pair-backend/issues/3 for details

**Comment by BenGitter** [comment]
Maybe this issue can be renamed to something like: "Make convertToMS.js pass all tests", instead of opening issues for other changes to convertToMS.js.

**Comment by JacksonBates** [comment]
Agreed. See #10
